version: 0.2
        
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.x
    commands:
      - echo Installing terser...
      - npm install -g terser
      - echo Installing clean-css-cli...
      - npm install -g clean-css-cli
  build:
    commands:
      - echo Build started on `date`
      - bash minify.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - barChart.html
    - css/*
    - js/*
    - data/*
    - gunIcon.png