version: 0.2
        
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.x
    commands:
      - echo Installing terser...
      - npm install -g terser
      - echo Installing clean-css-cli...
      - npm install -g clean-css-cli
  build:
    commands:
      - echo Build started on `date`
      - bash minify.sh
      - mkdir images
      - mv gunIcon.png images/
      - mv index.html wilmington-shootings.html
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - wilmington-shootings.html
    - barChart.html
    - css/*
    - js/*
    - data/*
    - gunIcon.png